# Generated by Django 4.1.1 on 2022-12-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_remove_music_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='link_song',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='Link'),
        ),
    ]
