# Generated by Django 4.1.1 on 2022-12-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_music_link_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='link_song',
        ),
        migrations.AddField(
            model_name='music',
            name='field_name',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
