# Generated by Django 4.1.1 on 2022-12-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_remove_music_link_song_music_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='field_name',
        ),
    ]
