# Generated by Django 4.1.1 on 2022-12-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_remove_music_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='date_created',
        ),
    ]
