# Generated by Django 4.1.1 on 2022-12-06 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_remove_music_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
